function stack = initialize(sections, overwrite)
%INITIALIZE Initializes a stack structure for an array of sections.
% Takes a cell array of:
% - Full paths to raw image section folders, or
% - Section structures generated by section.initialize()
% Or the path to the folder containing the raw image section folders.
%
% This also saves the stack metadata to cache in the data folder.

% Defaults
if nargin < 2
    overwrite = false;
end

fprintf('Initializing stack (%d sections)...\n', length(sections))
tic

% Check if user passed in path to the wafer folder
if ischar(sections)
    % Get a list of section folders
    sections = find_section_folders(sections, true);
end

% Make sure all the sections passed in are initialized
sec_array = cell(size(sections));
for i = 1:length(sections)
    sec = sections{i};
    
    % Initialize the section from its raw image folder
    if ischar(sec)
        sec_array{i} = section.initialize(sec);

    % This section was already pre-initialized
    elseif isstruct(sec)
        sec_array{i} = sec;

    else
        error(['Stack could not be initialized.\n' ...
            'Ensure that the input to the function is a CELL ARRAY of either:\n' ...
            '(1) Full paths to raw image section folders, or\n' ...
            '(2) Section structures from section.load() or section.initialize().'])
    end
end

% Instantiate the Stack class with these sections
stack = Stack(sec_array);

% Check if a metadata file already exists
if exist(stack.metadata_path, 'file') && ~overwrite
    warning(['Stack object that was just initialized was not saved to cache because the file already exists.\n' ...
        'Delete/rename the cached stack file or run stack.initialize() with the overwrite parameter set to true.%s'], '')
    return
end

% Save the initialized stack to cache
save(stack.metadata_path, 'stack')

fprintf('Saved metadata for stack (wafer %s / %d sections). [%.2fs]\n', stack.wafer, stack.num_sections, toc)
end

